// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUl-hJUpOp9wCCJsfKPdlxQXmpxRHL59M',
    appId: '1:1086146711395:web:e8299a6991b05bae410d56',
    messagingSenderId: '1086146711395',
    projectId: 'openlibrary-book-explorer',
    authDomain: 'openlibrary-book-explorer.firebaseapp.com',
    storageBucket: 'openlibrary-book-explorer.firebasestorage.app',
    measurementId: 'G-MMSFN95BCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrYVZDhdRs6Pi8TAOvwE9BwviI629vxRU',
    appId: '1:350744911073:android:31359c96c32e562388aba0',
    messagingSenderId: '350744911073',
    projectId: 'dattaram-work-dev',
    databaseURL: 'https://dattaram-work-dev-default-rtdb.firebaseio.com',
    storageBucket: 'dattaram-work-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfV4rjHkRqXuz1pGFdXAr9sw3nsVmZWI4',
    appId: '1:350744911073:ios:ed0636da864786fb88aba0',
    messagingSenderId: '350744911073',
    projectId: 'dattaram-work-dev',
    databaseURL: 'https://dattaram-work-dev-default-rtdb.firebaseio.com',
    storageBucket: 'dattaram-work-dev.firebasestorage.app',
    androidClientId: '350744911073-mline3bdl769d4b04q2b6atiio3se8no.apps.googleusercontent.com',
    iosClientId: '350744911073-vcvp7n3h7tbkrlv41m9nidolsvv3g96l.apps.googleusercontent.com',
    iosBundleId: 'com.example.openlibraryBookExplorer',
  );

}